spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: <REDACTED>
            clientSecret: <REDACTED>
            scope: read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
            userNameAttribute: name
